/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include <stdint.h>

/*
 * Memory addresses are recovered from memory mapping data sheet of STM32F407G-DISC1
 * Reference manual, pins are from schematics.
 *
 * Address list:
 *
 * -RCC: Reset-clock control register to enable clock on GPIO Port D
 *
 * -GPIOD_Pin_Mode: sets the mode of the pin in port D to be
 *  				input/output.
 *
 * -Output_pin: register to send data to the pin.
 */

#include <stdint.h>

int main(void)
{
	 uint32_t *pRCC_AHB1   	   =  (uint32_t*)0x40023830;
	 uint32_t *pGPIOD_pin_mode =  (uint32_t*)0x40020C00;
	 uint32_t *pOutPin         =  (uint32_t*)0x40020C14;

	// apply bitwise or to enable clock.

	*pRCC_AHB1 |= 0x08;

	/*
	 * clear GPIOD 24-25 bits. Leave others unaltered
	 * NOTE: Leaving commented because by default bits are already 0.
	 *       If on DEBUG these two bits are already active for some reason
	 *       then uncommed and clear the bit state.
	 *
	 *       Can be resued later to reset specific bit.
	 *
	 *       If you want to clear all the bits referr to the reset value in
	 *       the reference manual.
	 */

	//*pGPIOD_pin_mode &= 0xFCFFFFFF;

	//set bit 24 to 1 to apply output mode to pin 12 on port D
	*pGPIOD_pin_mode |= 0x01000000;

	//Activate PIND12, LED4 will turn on green
	*pOutPin |= 0x1000;

	//Deactivate PIND12, LED4 should turn off.

	*pOutPin &= 0xEFFF;

	for(;;);
}
