/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include <stdio.h>
#include <stdint.h>

/*
 * Reads status of PA0, if it has current (HIGH) then turn on LED4
 * if it's LOW, turn off the LED4.
 */

int main(void)
{
	 volatile uint32_t *pRCC_AHB1   		 =  (uint32_t*)0x40023830;
	 volatile uint32_t *pGPIOD_pin_moder     =  (uint32_t*)0x40020C00;
	 volatile uint32_t *pGPIOA_pin_moder     =  (uint32_t*)0x40020000;
	 volatile uint32_t *pOutPin 	   		 =  (uint32_t*)0x40020C14;
	 volatile const uint32_t *const pInPin   =  (uint32_t*)0x40020010;


	 //enable clock for both GPIOA and GPIOD
	*pRCC_AHB1 |= (1 << 0);
	*pRCC_AHB1 |= (1 << 3);

	*pGPIOD_pin_moder    |= (1 << 24);
	*pGPIOA_pin_moder    &= ~(3 << 0);

	while (1) {

		uint8_t pinState = (uint8_t)(*pInPin & 0x1);

		if (pinState) {
			*pOutPin   |= (1 << 12);
		} else {
			*pOutPin   &= ~(1 << 12);
		}
	}
}
